AlternetSiparisYazilimi/Controllers/SiparisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlternetSiparisYazilimi.Altyapi;
using AlternetSiparisYazilimi.Models; // Siparis sınıfı için
using AlternetSiparisYazilimi.Models.Soyut;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlternetSiparisYazilimi.Controllers
{
    //Sipariş sayfası için C# arka ucu
    public class SiparisController : Controller
    {
        private ISiparisAmbari SiparisAmbari;
        //public Sepet sepet;
        public SiparisController(ISiparisAmbari SiparisAmbari) //  SiparisAmbari Startup.cs'de Transient eklediğimiz için otomatik olarak EFSiparisAmbari nesnesi olarak ASP.NET Core dependency injection servisleri tarafından enjekte edilir.
        {
            this.SiparisAmbari = SiparisAmbari;
            //this.sepet = HttpContext.Session.GetJson<Sepet>("Sepet") ?? new Sepet();
        }

        //Bu metot yönetim paneli içindir.
        public ViewResult Listele()
        {
            //Sadece kargolanmamış olanları listeleyeceğim.
            return View(SiparisAmbari.Siparisler.Where(siparis => !siparis.Kargolandi));
        }
        [HttpPost]
        public IActionResult KargolandiOlarakIsaretle(int SiparisId)
        {
            Siparis siparis = SiparisAmbari.Siparisler.FirstOrDefault(s => s.SiparisID == SiparisId);
            if (siparis != null)
            {
                siparis.Kargolandi = true;
                SiparisAmbari.SiparisiKaydet(siparis); // Aynı nesneyi güncellemek için de SiparisiKaydet kullanılabilir. Çünkü AttachRange ile EF Core'a memory'de db objesi takibi yaptırılıyor.
            }
            return RedirectToAction(nameof(Listele));
}
       public ViewResult SiparisiVer()
       {
            return View(new Siparis());
       }
        [HttpPost]
        public IActionResult SiparisiVer(Siparis siparis)
        {         

            if (SepetiOturumdanGetir().SepetIcerik.Count() == 0)
            {
                ModelState.AddModelError("", "Üzgünüz bu işleminizi gerçekleştiremiyoruz, sepetiniz şu an boş...");
            }

            if (ModelState.IsValid) // Gelen model sipariş'de model hatası yok ise...
            {
                //Sepet içeriğini makulen Session'dan çekeceğiz.
                siparis.SepetSatirlari = SepetiOturumdanGetir().SepetIcerik.ToArray();
                SiparisAmbari.SiparisiKaydet(siparis); // Siparişi veritabanına kaydet
                return RedirectToAction(nameof(SiparisAlindi));
                //RedirectToAction IActionResult implemente eder ViewResult getirmez !
            }
            else // Model geçerli değil ise model SiparisVer cshtml view'süne tekrar gönder ve görüntüle.
            {
                return View(siparis);
            }

        }

        public ViewResult SiparisAlindi()
        {
            SepetiYoket();
            //Sipariş için bir teşekkür mesajı yayınlayalım.
            return View();
        }

        public void SepetiOturumaKaydet(Sepet sepet)
        {
            HttpContext.Session.SetJson("Sepet", sepet);  //Session içerisindeki metotlar(Set gibi) sadece byte[] ve string bilgi kaydedebiliyor. Ben bu ISession/Session sınıfını "Altyapı Klasöründe" SessionGenislemeMetotları sınıfındakı genişleme metotları ile JSON işleyebilecek şekilde genişlettim.
        }
        //public void SepetiOturumaKaydet()
        //{
        //    HttpContext.Session.SetJson("Sepet", sepet);  //Session içerisindeki metotlar(Set gibi) sadece byte[] ve string bilgi kaydedebiliyor. Ben bu ISession/Session sınıfını "Altyapı Klasöründe" SessionGenislemeMetotları sınıfındakı genişleme metotları ile JSON işleyebilecek şekilde genişlettim.
        //}
        public Sepet SepetiOturumdanGetir() // Sepet boş ise yeni bir boş Sepet nesnesi getirir.
        {
            return HttpContext.Session.GetJson<Sepet>("Sepet") ?? new Sepet(); //Kullanıcı oturumundaki sepet anahtarındaki değer boş ise yeni bir Sepet nesnesi oluştur ve SepetiOturumdanGetir fonksiyonu dönüş değeri olarak geri döndür.
        }
        private void SepetiYoket() // Sepet boş ise yeni bir boş Sepet nesnesi getirir.
        {
           HttpContext.Session.Remove("Sepet"); //Kullanıcı oturumundaki sepet anahtarındaki değer boş ise yeni bir Sepet nesnesi oluştur ve SepetiOturumdanGetir fonksiyonu dönüş değeri olarak geri döndür.
        }



    }
}

AlternetSiparisYazilimi/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlternetSiparisYazilimi.Models.Soyut;
using AlternetSiparisYazilimi.Models;
using AlternetSiparisYazilimi.Models.ViewModels;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlternetSiparisYazilimi.Controllers
{
    public class UrunController : Controller //ÜRÜNLERİMİZ MENÜSÜ KONTROLLERİ
    {
        
        //Microsoft.AspNetCore.Hosting.IHostingEnvironment env;
        private IUrunAmbari UrunAmbari;
        public UrunController(IUrunAmbari UrunAmbari)
        {
            this.UrunAmbari = UrunAmbari;
            SayfaBoyutu = 5;
            //this.env = env;
        }
        public IActionResult Index()
        {
            return View();
          
        }
        public int SayfaBoyutu;
       
        //Sayfa başı sayfalama(1,2,3..) bölümünde seçilen eleman değişeceği için buraya bir ViewModel ekleyeceğim. Sayfalayici ve Urunler bir arada olacak.
        public ViewResult Listele(string Kategori, int SayfaNo= 1, string Arama=null)
        {
            //string dosyaYolu = System.IO.Path.Combine(env.WebRootPath/*wwwroot*/, "resimler", "UrunResimleri", $"resim{1}.jpg").ToString();
            //BURANIN URL'Yİ XX.COM/IMAGES/..RESİM1.jpg şeklinde vermesi gerekiyor olabilir. ancak burası c:... şeklinde verdiği için muhtemelen sorun çıkıyor


            ViewData["ParaBirimi"] = RegionInfo.CurrentRegion.CurrencySymbol;
            
            IQueryable<Urun> sayfaUrunleri = UrunAmbari.Urunler.Where(u=> u.Kategorisi == Kategori || Kategori== null ).OrderBy(u=> u.UrunID).Skip((SayfaNo-1)* SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            if (Arama != null)
            {
            
            sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).Where(u=> u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama) || u.Fiyat.ToString() == Arama).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            }
            Sayfalayici s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori ==null ? UrunAmbari.Urunler.Count(): UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Count() };
            if (Arama != null)
            {
                s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() };
            }
            IList<string> FiltreleMenusu = UrunAmbari.Urunler.Select(ss => ss.Kategorisi).Distinct().OrderBy(o => o).ToList();
           

            SelectList KategoriFiltreleMenusu = new SelectList(FiltreleMenusu, Kategori);
            

            ViewData["KategoriFiltreleMenusu"] = KategoriFiltreleMenusu;   //select listesi/drop down list ve seçilen öğe.
            ViewData["AramaDegeri"] = Arama;
            UrunlerViewModel UrunlerVeSayfalama = new UrunlerViewModel { urunler = sayfaUrunleri, sayfalayici = s , Kategorim=Kategori};
            return View(UrunlerVeSayfalama);

            
        }
        public PartialViewResult JQueryAjaxListele(string Kategori, int SayfaNo = 1, string Arama = null)
        {
            string x = RouteData.Values["controller"].ToString();
            string xy = RouteData.Values["action"].ToString();
            //string dosyaYolu = System.IO.Path.Combine(env.WebRootPath/*wwwroot*/, "resimler", "UrunResimleri", $"resim{1}.jpg").ToString();
            //BURANIN URL'Yİ XX.COM/IMAGES/..RESİM1.jpg şeklinde vermesi gerekiyor olabilir. ancak burası c:... şeklinde verdiği için muhtemelen sorun çıkıyor

            
            ViewData["TurkParaBirimi"] = RegionInfo.CurrentRegion.CurrencySymbol;

            IQueryable<Urun> sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            if (Arama != null)
            {
                //ARAMA KUTUCUĞU KATEGORİ FİLTRELEMEZ NORMAL OLARAK !! İSTENİRSE || u.Kategorisi.Contains(Arama) EKLENEBİLİR.
                sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama) || u.Fiyat.ToString() == Arama ).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            }
            Sayfalayici s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Count() };
            if (Arama != null)
            {
                s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() };
            }
            IList<string> FiltreleMenusu = UrunAmbari.Urunler.Select(ss => ss.Kategorisi).Distinct().OrderBy(o => o).ToList();


            SelectList KategoriFiltreleMenusu = new SelectList(FiltreleMenusu, Kategori);


            ViewData["KategoriFiltreleMenusu"] = KategoriFiltreleMenusu;   //select listesi/drop down list ve seçilen öğe.
            ViewData["AramaDegeri"] = Arama;
            UrunlerViewModel UrunlerVeSayfalama = new UrunlerViewModel { urunler = sayfaUrunleri, sayfalayici = s, Kategorim = Kategori };
            return PartialView(UrunlerVeSayfalama);


        }

        public FileContentResult resmiGetir(int id)
        {
            
            byte[] byteDizisi = UrunAmbari.Urunler.Where(u=>u.UrunID == id).FirstOrDefault()?.UrunResmi;
            if (byteDizisi != null)
            {
                return new FileContentResult(byteDizisi, "image/jpeg");
            }
            else
            {
                return null;
            }
        }

    }
}

AlternetSiparisYazilimi/Controllers/YonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlternetSiparisYazilimi.Models.Soyut;
using AlternetSiparisYazilimi.Models;

namespace AlternetSiparisYazilimi.Controllers
{
    public class YonetimController : Controller
    {
        private IUrunAmbari UrunAmbari;
        public YonetimController(IUrunAmbari UrunAmbari)
        {
            this.UrunAmbari = UrunAmbari;
        }
        public ViewResult Index() => View(UrunAmbari.Urunler); // 

        public ViewResult Duzenle(int UrunID) // sadece id bilgisini almamız yeterli.
        { 
        return View(UrunAmbari.Urunler.FirstOrDefault(u => u.UrunID == UrunID));
        }

        [HttpPost]
        public IActionResult Duzenle(Urun urun)
        {
            if (ModelState.IsValid) // Urun nesnesi doğrulamadan geçtiyse
            {
                UrunAmbari.UrunuKaydet(urun);
                TempData["Bilgi"] = $"{urun.UrunID} ID'li ve {urun.Isim} adlı ürününüz kaydedildi.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(); // Model'den model bağlama ile gelen bilgiler de validasyon/doğrulama hatası var, tekrar aynı sayfayı hatalarla birlikte yazdır.
            }
           
        }
        public IActionResult UrunOlustur()
        {
            return View("Duzenle", new Urun()); // Duzenle.cshtml view'sünü hem ürün oluşturma hem ürün içeriği değişkliği için kullanmış olduk.
        }
        public IActionResult UrunuSil(int UrunID)
        {
            Urun silinenUrun = UrunAmbari.UrunuSil(UrunID);
            if (silinenUrun!=null)
            {
                TempData["Bilgi"] = $"{silinenUrun.UrunID} ID'li ve {silinenUrun.Isim} adlı ürününüz silindi.";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

AlternetSiparisYazilimi/Views/Yonetim/Duzenle.cshtml
@model AlternetSiparisYazilimi.Models.Urun

@{
    ViewData["Title"] = "Yönetim Paneli";
    if (ViewContext.RouteData.Values["action"].ToString() == "UrunOlustur")
    {
        ViewData["SubTitle"] = "Ürün Oluştur";

    }
    else
    {
        ViewData["SubTitle"] = "Ürün'ü Düzenle";
    }


    Layout = "~/Views/Shared/_YonetimPaneliLayout.cshtml";
}
@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
  
}
<h4>Ürün</h4>
<hr />
<div class="row pl-1">
    <div class="col-md-4">
        <form asp-action="Duzenle">
            @* model only dersen sadece ilgili kutucukların yanında hatalar gösterilir. all dersen tüm hatalar en tepede ayrıyeten gösterilir.*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UrunID" />
            <div class="form-group">
                <label asp-for="Isim" class="control-label"></label>
                <input asp-for="Isim" class="form-control" />
                <span asp-validation-for="Isim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aciklama" class="control-label"></label>
                <input asp-for="Aciklama" class="form-control" />
                <span asp-validation-for="Aciklama"  class="text-danger"></span>
            </div>
            <div class="form-group">


                <label asp-for="Fiyat" class="control-label"></label>(@System.Globalization.CultureInfo.CurrentCulture kültürü için ondalık sayı ayraçı "@System.Globalization.CultureInfo.CurrentUICulture.NumberFormat.CurrencyDecimalSeparator"dır)
                @*<input asp-for="Fiyat" class="form-control" />*@
                @* jquery obstrusive validasyon da lokaliasyon yapılmadığından . ve , den dolayı hatalı çalışan data-val-number veri sıfatını iptal etmek zorunda kaldım bu doğrulama aşağıdaki REGEX ifadesi ile başarıldı  *@
                <input class="form-control" type="text" data-val="true" data-val-regex="Fiyat değeri bir sayı olmalıdır" data-val-regex-pattern="^(\d*\,)?\d+$"
                       data-val-required="Lütfen bir fiyat belirtiniz"                                           
                       id="Fiyat" name="Fiyat" value="@Model.Fiyat" />
                <span asp-validation-for="Fiyat" class="text-danger"></span>


            </div>
            <div class="form-group">
                <label asp-for="Kategorisi" class="control-label"></label>
                <input asp-for="Kategorisi" class="form-control" />
                <div><span asp-validation-for="Kategorisi" class="text-danger"></span></div>
            </div>

            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
</div>

AlternetSiparisYazilimi/Views/Yonetim/Index.cshtml
@model IEnumerable<AlternetSiparisYazilimi.Models.Urun>

@{
    ViewData["Title"] = "Yönetim Paneli";
    ViewData["SubTitle"] = "Ürün Kataloğu";
    Layout = "~/Views/Shared/_YonetimPaneliLayout.cshtml";
}
Uygulama Dil/Bölge Kültürü: @System.Globalization.CultureInfo.CurrentUICulture
<div class="text-left m-2">
    <a asp-action="Listele" asp-controller="Urun" class="btn btn-outline-secondary">Geri Dön</a>
    <a asp-action="Listele" asp-controller="Siparis" class="btn btn-info">Gelen Siparişler</a>
    <a asp-action="UrunOlustur" class="btn btn-primary">Yeni Ürün Ekle</a>
</div>
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-right">ID</th>
        <th>Ürün Adı</th>
        <th>Açıklama</th>
        <th>Kategori</th>
        <th class="text-right">Fiyat</th>
        <th class="text-center">Ne Yapmak İstersiniz?</th>
    </tr>
    @foreach (var u in Model)
    {
        <tr>
            <td class="text-right">@u.UrunID</td>
            <td>@u.Isim</td>
            <td>@u.Aciklama</td>
            <td>@u.Kategorisi</td>
            <td class="text-right">@u.Fiyat.ToString("c")</td>
            <td class="text-center">

                <form asp-action="UrunuSil" method="post">
                    @*bu a yi form içine aldım ki düzenle ve sil butonu yan yana olsun, form ile bir alakası yok*@
                    <a asp-action="Duzenle" asp-route-UrunID="@u.UrunID" class="btn btn-sm btn-success">
                        Düzenle
                    </a>

                    <input type="hidden" name="UrunID" value="@u.UrunID" />
                    <button type="submit" class="btn btn-danger btn-sm">
                        Sil
                    </button>
                </form>
            </td>
        </tr>
    }
</table>