AlternetSiparisYazilimi/Components/AramaViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace AlternetSiparisYazilimi.Components
{
    public class AramaViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

AlternetSiparisYazilimi/Components/SepetViewComponent.cs
using AlternetSiparisYazilimi.Altyapi;
using AlternetSiparisYazilimi.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlternetSiparisYazilimi.Components
{
    public class SepetViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            int adet = 0;
            Sepet s = ViewContext.HttpContext.Session.GetJson<Sepet>("Sepet");
            if (s == null)
            {
                adet = 0;
            }
            else if (s != null && s.SepetIcerik.Count() == 0)
            {
                adet = 0;
            }
            else
            {
                adet = s.SepetIcerik.Count();
            }
            ViewData["Adet"] = adet;
            return View();
        }

    }
}

AlternetSiparisYazilimi/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlternetSiparisYazilimi.Models.Soyut;
using AlternetSiparisYazilimi.Models;
using AlternetSiparisYazilimi.Models.ViewModels;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlternetSiparisYazilimi.Controllers
{
    public class UrunController : Controller //ÜRÜNLERİMİZ MENÜSÜ KONTROLLERİ
    {
        
        //Microsoft.AspNetCore.Hosting.IHostingEnvironment env;
        private IUrunAmbari UrunAmbari;
        public UrunController(IUrunAmbari UrunAmbari)
        {
            this.UrunAmbari = UrunAmbari;
            SayfaBoyutu = 5;
            //this.env = env;
        }
        public IActionResult Index()
        {
            return View();
          
        }
        public int SayfaBoyutu;
       
        //Sayfa başı sayfalama(1,2,3..) bölümünde seçilen eleman değişeceği için buraya bir ViewModel ekleyeceğim. Sayfalayici ve Urunler bir arada olacak.
        public ViewResult Listele(string Kategori, int SayfaNo= 1, string Arama=null)
        {
            //string dosyaYolu = System.IO.Path.Combine(env.WebRootPath/*wwwroot*/, "resimler", "UrunResimleri", $"resim{1}.jpg").ToString();
            //BURANIN URL'Yİ XX.COM/IMAGES/..RESİM1.jpg şeklinde vermesi gerekiyor olabilir. ancak burası c:... şeklinde verdiği için muhtemelen sorun çıkıyor


            ViewData["ParaBirimi"] = RegionInfo.CurrentRegion.CurrencySymbol;
            
            IQueryable<Urun> sayfaUrunleri = UrunAmbari.Urunler.Where(u=> u.Kategorisi == Kategori || Kategori== null ).OrderBy(u=> u.UrunID).Skip((SayfaNo-1)* SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            if (Arama != null)
            {
            
            sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).Where(u=> u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama) || u.Fiyat.ToString() == Arama).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            }
            Sayfalayici s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori ==null ? UrunAmbari.Urunler.Count(): UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Count() };
            if (Arama != null)
            {
                s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() };
            }
            IList<string> FiltreleMenusu = UrunAmbari.Urunler.Select(ss => ss.Kategorisi).Distinct().OrderBy(o => o).ToList();
           

            SelectList KategoriFiltreleMenusu = new SelectList(FiltreleMenusu, Kategori);
            

            ViewData["KategoriFiltreleMenusu"] = KategoriFiltreleMenusu;   //select listesi/drop down list ve seçilen öğe.
            ViewData["AramaDegeri"] = Arama;
            UrunlerViewModel UrunlerVeSayfalama = new UrunlerViewModel { urunler = sayfaUrunleri, sayfalayici = s , Kategorim=Kategori};
            return View(UrunlerVeSayfalama);

            
        }
        public PartialViewResult JQueryAjaxListele(string Kategori, int SayfaNo = 1, string Arama = null)
        {
            string x = RouteData.Values["controller"].ToString();
            string xy = RouteData.Values["action"].ToString();
            //string dosyaYolu = System.IO.Path.Combine(env.WebRootPath/*wwwroot*/, "resimler", "UrunResimleri", $"resim{1}.jpg").ToString();
            //BURANIN URL'Yİ XX.COM/IMAGES/..RESİM1.jpg şeklinde vermesi gerekiyor olabilir. ancak burası c:... şeklinde verdiği için muhtemelen sorun çıkıyor

            
            ViewData["TurkParaBirimi"] = RegionInfo.CurrentRegion.CurrencySymbol;

            IQueryable<Urun> sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            if (Arama != null)
            {
                //ARAMA KUTUCUĞU KATEGORİ FİLTRELEMEZ NORMAL OLARAK !! İSTENİRSE || u.Kategorisi.Contains(Arama) EKLENEBİLİR.
                sayfaUrunleri = UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori || Kategori == null).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama) || u.Fiyat.ToString() == Arama ).OrderBy(u => u.UrunID).Skip((SayfaNo - 1) * SayfaBoyutu).Take(SayfaBoyutu); // 1-10 ürünlerini 1. sayfa olarak al, sonra 11-20 ürünlerini 2. sayfa olarak al. sonra 21 30 ürünlerini 3. sayfa olarak al.../*Kategori değeri null ise hepsini getirsin*/
            }
            Sayfalayici s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Count() };
            if (Arama != null)
            {
                s = new Sayfalayici { SayfaBasiOgeler = SayfaBoyutu, SuAnKiSayfa = SayfaNo, ToplamOgeler = Kategori == null ? UrunAmbari.Urunler.Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() : UrunAmbari.Urunler.Where(u => u.Kategorisi == Kategori).Where(u => u.Aciklama.Contains(Arama) || u.Isim.Contains(Arama)).Count() };
            }
            IList<string> FiltreleMenusu = UrunAmbari.Urunler.Select(ss => ss.Kategorisi).Distinct().OrderBy(o => o).ToList();


            SelectList KategoriFiltreleMenusu = new SelectList(FiltreleMenusu, Kategori);


            ViewData["KategoriFiltreleMenusu"] = KategoriFiltreleMenusu;   //select listesi/drop down list ve seçilen öğe.
            ViewData["AramaDegeri"] = Arama;
            UrunlerViewModel UrunlerVeSayfalama = new UrunlerViewModel { urunler = sayfaUrunleri, sayfalayici = s, Kategorim = Kategori };
            return PartialView(UrunlerVeSayfalama);


        }

        public FileContentResult resmiGetir(int id)
        {
            
            byte[] byteDizisi = UrunAmbari.Urunler.Where(u=>u.UrunID == id).FirstOrDefault()?.UrunResmi;
            if (byteDizisi != null)
            {
                return new FileContentResult(byteDizisi, "image/jpeg");
            }
            else
            {
                return null;
            }
        }

    }
}

AlternetSiparisYazilimi/Controllers/YonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AlternetSiparisYazilimi.Models.Soyut;
using AlternetSiparisYazilimi.Models;

namespace AlternetSiparisYazilimi.Controllers
{
    public class YonetimController : Controller
    {
        private IUrunAmbari UrunAmbari;
        public YonetimController(IUrunAmbari UrunAmbari)
        {
            this.UrunAmbari = UrunAmbari;
        }
        public ViewResult Index() => View(UrunAmbari.Urunler); // 

        public ViewResult Duzenle(int UrunID) // sadece id bilgisini almamız yeterli.
        { 
        return View(UrunAmbari.Urunler.FirstOrDefault(u => u.UrunID == UrunID));
        }

        [HttpPost]
        public IActionResult Duzenle(Urun urun)
        {
            if (ModelState.IsValid) // Urun nesnesi doğrulamadan geçtiyse
            {
                UrunAmbari.UrunuKaydet(urun);
                TempData["Bilgi"] = $"{urun.UrunID} ID'li ve {urun.Isim} adlı ürününüz kaydedildi.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(); // Model'den model bağlama ile gelen bilgiler de validasyon/doğrulama hatası var, tekrar aynı sayfayı hatalarla birlikte yazdır.
            }
           
        }
        public IActionResult UrunOlustur()
        {
            return View("Duzenle", new Urun()); // Duzenle.cshtml view'sünü hem ürün oluşturma hem ürün içeriği değişkliği için kullanmış olduk.
        }
        public IActionResult UrunuSil(int UrunID)
        {
            Urun silinenUrun = UrunAmbari.UrunuSil(UrunID);
            if (silinenUrun!=null)
            {
                TempData["Bilgi"] = $"{silinenUrun.UrunID} ID'li ve {silinenUrun.Isim} adlı ürününüz silindi.";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

AlternetSiparisYazilimi/Views/Shared/UrunSayfaParcasi.cshtml
@model Urun
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    
*@
@{

}
<style>
    button:hover .sepetLogo {
        padding-top: 20px;
        padding-left:20px;
    }
    .gecis {
        background-color: aliceblue;
        -webkit-transition: background-color 3s;
        -moz-transition: background-color 3s;
        transition: background-color 3s;
    }
    .gecis:hover{
        background-color:antiquewhite
    }
    tr:hover {
        /*when hovering an item:*/
        background-color:aliceblue;
        -moz-transition: background-color linear 0.2s;
        -webkit-transition: background-color linear 0.2s;
        transition: background-color linear 0.2s;
    }

</style>
<tr>
    <td>

        @if (Model.UrunResmi != null)
        {
        <div class="pull-left">
            <img height="50" width= "50" src="@Url.Action("resmiGetir", "Urun", new { id = 1 })" alt="Ürün Resmi" />
        </div>
        }
    </td>
    
    <td style="width:5px">
        <h6>@Model.UrunID</h6>
    </td>
    <td>
        <h6>@Model.Isim</h6>
    </td>
    <td class="card-text p-1">
        @Model.Aciklama
    </td>
    <td class="badge badge-pill badge-default">

        <h6>@Model.Fiyat@ViewData["ParaBirimi"] </h6>
    </td>
    <td>
        <h6>@Model.Kategorisi</h6>
    </td>
    @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    <td>
       
     
        <form asp-action="SepeteEkle" asp-controller="Sepet" method="post">
            <input type = "hidden" asp-for= "@Model.UrunID" /> @*Ürün ID değerini gönderebilmek için *@
            <input type = "hidden" name = "ReturnURL" value = "@ViewContext.HttpContext.Request.URLAdresYoluVeSorguIfadesiniGetir()" /> @*Burada sepet sayfasındaki "geri dön" butonunun ve de sepet'e ekleme yapıldıktan sonra gidilecek URL adresi depolanıyor *@
            <div style="border-radius: 100px; background-color:white; color:crimson; max-height:50px;" class="menuBtnYeni2Checked">
                <span style="font: bold 12px Arial; color:black">Adet:</span>
                <input name="Adet" value="1" style="width:25px; border-radius: 5px;" class="table-bordered" />
                <button style="border-radius: 55px;" class="btn btn-danger btn-sm" type="submit">
                    <img class="sepetLogo" src="~/resimler/sepet.png" width="20" height="20" /> Sepet'e Ekle
                </button>

            </div>

        </form>
    </td>
</tr>

AlternetSiparisYazilimi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/jpg" href="~/resimler/minilogoTrans5.png">
    <link asp-href-include="/lib/bootstrap/dist/**/*.min.css" rel="stylesheet" /> @*asp-href-include ** kullanmamıza olanak verdi.*@
    <link asp-href-include="/lib/menu_css.css" rel="stylesheet" />


    <script src="~/lib/jquery/dist/jquery.js"></script>
    @*<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>*@
    @*<script src="~/AlternetJS/AJAXFonksiyonlari.js"></script>*@
    <script>//KATEGORİ FİLTRELEME JQUERY AJAX İSTEKLERİ, ONCHANGE >> LOAD

$(document).ready(function () {
    $("#Kategori").change(function () {
        var kategori = $("#Kategori").val();
        kategori = kategori.replace(/\s+/g, '%20') // Bu ifade boşlukları %20 ile değiştirir. Aksi halde boşluklu olarak bir değişken ile istek(query) yapıldığında( Soğuk Algınlığı gibi) dönüşüm JQUERY ile otomatik yapılmıyor.
        //alert(kategori); // Test et.
        $("#urunListesi").html('<div class="YukleDiv"><img class="yukleniyorGif" src="yukleniyor.gif"/><span class="yukleniyorYazisi">Yükleniyor</span></div>').load('@(Url.Action("JQueryAjaxListele", "Urun"))?Kategori=' + kategori);
        //Tüm ürünler seçilidğinde "" null değeri gönderilir ve bu Controller(ya da Web API) fonksiyonları tarafından algılanarak tüm ürünler olarak sorgu yapılır.
    });
});
        //SAYFALAYICI JQUERY AJAX İSTEKLERİ ONCLICK >> LOAD
        //@* $(document).ready(function () {
        //    $(".SayfaLinki").click(function () {
        //        var sayfa = $(this).html();
        //        // sayfa = sayfa.replace(/\s+/g, '%20') // Bu ifade boşlukları %20 ile değiştirir. Aksi halde boşluk olarak istek yapıldığında dönüşüm JQUERY ile otomatik yapılmıyor.
        //        alert(sayfa); // Test et.
        //        $("#urunListesi").load('@(Url.Action("JQueryAjaxListele", "Urun"))?SayfaNo=' + sayfa);
        //        //Tüm ürünler seçilidğinde "" null değeri gönderilir ve bu Controller(ya da Web API) fonksiyonları tarafından algılanarak tüm ürünler olarak sorgu yapılır.
        //    });
        //});*@

             //SAYFALAYICI VERSIYON 2 JQUERY AJAX İSTEKLERİ ONCLICK >> LOAD
            //SayfalayiciHTMLRendererHelper sınıfı ÜZERİNDE  yeniLink.Attributes.Add("onclick", "SayfayaGit("+sayfa+")"); İLE BAŞARILDI

                var SayfayaGit = function (sayfaNo, kategori) {
    kategori = kategori.replace(/\s+/g, '%20') // Bu ifade boşlukları %20 ile değiştirir. Aksi halde boşluk olarak istek yapıldığında dönüşüm JQUERY ile otomatik yapılmadığı için boş sonuç döner.
    //alert(kategori); // Test et. Başarılı
    $("#urunListesi").html('<div class="YukleDiv"><img class="yukleniyorGif" src="yukleniyor.gif"/><span class="yukleniyorYazisi">Yükleniyor</span></div>').load('@(Url.Action("JQueryAjaxListele", "Urun"))?Kategori=' + kategori + '&SayfaNo=' + sayfaNo);
    //Tüm ürünler seçilidğinde "" null değeri gönderilir ve bu Controller(ya da Web API) fonksiyonları tarafından algılanarak tüm ürünler olarak sorgu yapılır.
}



//ARAMA KUTUCUĞU JQUERY AJAX INPUT EVENT(herhangi bir değer girilmesi VE DE SİLİNMESİ DAHİL) >> LOAD

$(document).ready(function () {
    $("#aramaKutucugu").bind('input', function () {
        var aranacakDeger = $("#aramaKutucugu").val();
        // sayfa = sayfa.replace(/\s+/g, '%20') // Bu ifade boşlukları %20 ile değiştirir. Aksi halde boşluk olarak istek yapıldığında dönüşüm JQUERY ile otomatik yapılmıyor.

        $("#urunListesi").html('<div class="YukleDiv"><img class="yukleniyorGif" src="yukleniyor.gif"/><span class="yukleniyorYazisi">Yükleniyor</span></div>').load('@(Url.Action("JQueryAjaxListele", "Urun"))?Arama=' + aranacakDeger);

    });


        });
    </script>
    @RenderSection("Scripts", false) @* false olarak atamazssak layout'u kullanan tüm view'lerde @section Scripts tanımlı olmak zorunda olacaktı. biz veri doğrulamayı sadece bazı yerlerde kullanacağız*@

    <title>Alternet | İlaç Sipariş </title>
    <style>

        #inp1:hover {
            border-color: indigo;
        }

        .yukleniyorGif {
            display: inline-block
        }

        .yukleniyorYazisi {
            vertical-align: central;
            display: inline-block;
            font: bold;
            padding-left: 5px;
            padding-top: 10px;
            opacity: 0.9;
            -webkit-transition: opacity 0.5s ease-in-out;
            -moz-transition: opacity 0.5s ease-in-out;
            transition: opacity 0.5s ease-in-out;
        }

        .YukleDiv {
            padding-top: 100px;
            padding-left: 50px;
        }
    </style>
</head>

<body>

    <div style="float:left; position:absolute; top:30px;">

    </div>
    <div style="padding-left:12%; padding-right:12%; ">
        <nav>
            <div id="categories" style="float:left; position:absolute; top:0px; ">
                <a href="@Url.Action(controller: "Urun", action:"Listele")" style="text-decoration:none;">
                    <img src="~/resimler/mainLogo-256x120.png" href="#" alt="Alternet" style="height:40px; vertical-align:top; " /><img />
                </a>
                @await Component.InvokeAsync("NavigationMenu")
                &emsp;
                @await Component.InvokeAsync("Sepet")


            </div>
        </nav>
        @*controller değeri sepet ise arama kutucuğunu gizle*@
        @if (ViewContext.RouteData.Values["controller"].ToString() == "Urun")
        {
            @await Component.InvokeAsync("Arama");
        }


        <div style="-webkit-box-shadow: 0px -1px 6px 1px rgba(77,77,77,0.28); -moz-box-shadow: 0px -1px 6px 1px rgba(77,77,77,0.28); box-shadow: 0px -1px 6px 1px rgba(77,77,77,0.28); margin-top:40px; -webkit-border-bottom-right-radius: 30px; -webkit-border-top-left-radius: 30px; margin-top:45px  ">
            <div id="urunListesi">

                @RenderBody()


                @*burası Partial View ile de yapılabilir*@
            </div>
            @*controller değeri sepet ise kategori filtreleyiciyi gizle*@
            @if (ViewContext.RouteData.Values["controller"].ToString() == "Urun")
            {
                <div id="filtreBolumu" style="float:right; margin-top:-30px; margin-right:15px">
                    <form method="post">
                        <span>Kategori Filtrele</span>
                        <select name="Kategori" id="Kategori" asp-items="@ViewData["KategoriFiltreleMenusu"] as SelectList" style="background-color:white; color:black" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <option value="">Tüm Ürünler</option>
                        </select>
                    </form>
                </div>
            }


            <footer style="margin-top: -20px; padding-top:30px; padding-bottom:10px; margin-bottom:10px; height:50px; text-align:center; font-family: 'Microsoft Sans Serif';">  <br />Telif Hakkı © 2019, Alternet Yazılım Ltd., Tüm Hakları Saklıdır.<br /><span style="font-size:13px; color:rosybrown">ASP.NET Core MVC 2, Entity Framework Core, C#, HTML5, CSS3, Bootstrap, JQuery UI, JQuery AJAX ve SQL Server Express kullanılmıştır. <br /><a target="_blank" href="https://www.linkedin.com/in/tadakoglu/">Geliştirici: Tayfun ADAKOĞLU || Linkedin Profile</a></span></footer>
            @if (ViewContext.RouteData.Values["controller"].ToString() == "Urun")
            {
                <a asp-controller="Yonetim" asp-action="Index" style="text-decoration:none " class="btn btn-outline-danger float-right"><h6>Yönetim<br />Paneli</h6></a>
            }

        </div>
    </div>


  
</body>

</html>

AlternetSiparisYazilimi/Views/Shared/_YonetimPaneliLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/jpg" href="~/resimler/minilogoTrans.png">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <style>
        .input-validation-error {
            border-color: ghostwhite;
            background-color: #fee;
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", false) @* false olarak atamazssak layout'u kullanan tüm view'lerde @section Scripts tanımlı olmak zorunda olacaktı. biz veri doğrulamayı sadece bazı yerlerde kullanacağız*@

</head>

<body style="padding-left:5%; padding-right:5%">
    @* margin 3 padding 3%*@
    <div style="display: inline-block; width:100%; background-color:azure">
        <div style="float:left; color: white; padding-right:10px" class="badge-danger  text-capitalize text-center navbar-text"><h5> @ViewData["Title"]</h5></div>
        <div style="float:left; color: white; padding-right:10px" class="badge-default  text-capitalize text-center navbar-text"><h5> > </h5></div>
        <div style="float:left; color: white; padding-right:10px; opacity:0.8" class="badge-danger  text-capitalize text-center navbar-text"><h5> @ViewData["SubTitle"]</h5></div>
        <a style="float:right" asp-action="Listele" asp-controller="Urun" class="btn btn-secondary m-2">Oturumu Kapat</a>
    </div>
    @if (TempData["Bilgi"] != null)
    {
        <div class="alert alert-info">@TempData["Bilgi"]</div>
    }
    @RenderBody()
    <footer style="margin-bottom:75px; height:50px; text-align:center; font-family: 'Microsoft Sans Serif';">  <br />Telif Hakkı © 2019, Alternet Yazılım Ltd., Tüm Hakları Saklıdır.<br /><span style="font-size:13px; color:rosybrown">ASP.NET Core MVC 2, Entity Framework Core, C#, HTML5, CSS3, Bootstrap, JQuery UI, JQuery AJAX ve SQL Server Express kullanılmıştır. <br /><a target="_blank" href="https://www.linkedin.com/in/tadakoglu/">Geliştirici: Tayfun ADAKOĞLU || Linkedin Profile</a></span></footer>

</body>

</html>